using System;

namespace Sony.MonitorControl.Internal;

public sealed class LegacyVmsContainer : ILegacySdcpContainer
{
	private byte[] data;

	private ushort length;

	private const byte CMD_COMMON = 0;

	private const byte CMD_HOST_CONTROL = 4;

	private const byte CMD_SYSTEM_CONFIGURATION = 8;

	private const byte CMD_ADJUSTMENT = 16;

	private const byte CMD_INFORMATION = 24;

	private const byte CMD_UNIVERSAL_FUNCTION_COMMON = 32;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION = 33;

	private const byte CMD_UNIVERSAL_FUNCTION_SIGNAL_PATH_FUNCTION = 34;

	private const byte CMD_UNIVERSAL_FUNCTION_MAKER_FUNCTION = 35;

	private const byte CMD_UNIVERSAL_FUNCTION_FPD_LCD_UNIQUE_FUNCTION = 36;

	private const byte CMD_UNIVERSAL_FUNCTION_SCALING_PIXEL_FUNCTION = 37;

	private const byte CMD_UNIVERSAL_FUNCTION_PICTURE_AND_PICTURE_FUNCTION = 38;

	private const byte CMD_UNIVERSAL_FUNCTION_ANALOG_FUNCTION = 39;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION = 48;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER = 50;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING = 52;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE = 64;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION = 66;

	private const byte CMD_DISPLAY_FUNCTION_INTERNAL_SIGNAL = 67;

	private const byte CMD_DISPLAY_FUNCTION_PARALLEL_REMOTE = 68;

	private const byte CMD_DISPLAY_FUNCTION_VARIOUS_SETTING = 69;

	private const byte CMD_COPY_SYSTEM = 80;

	private const byte CMD_AREA_SETTING = 84;

	private const byte CMD_PACKEGED_STATUS = 96;

	private const byte CMD_COMMON_PRODUCT_INFOMATION = 0;

	private const byte CMD_COMMON_START_CONTROL = 1;

	private const byte CMD_COMMON_PRODUCT_SOFTWARE_VERSION = 2;

	private const byte CMD_COMMON_SYSTEM_CONDITON = 3;

	private const byte CMD_HOST_CONTROL_SENSE_THE_RIGHT_OF_SET_OPERATION = 0;

	private const byte CMD_HOST_CONTROL_THE_RIGHT_OF_SET_OPEATION = 0;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_SYSTEM_TYPE = 0;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_MENU_IS_EXECUTABLE = 1;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_PACKAGED_STATUS = 2;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_PACKAGED_SET = 3;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_SNMP_CONTACT = 4;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_SNMP_NAME = 5;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_SNMP_LOCATION = 6;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_SNMP_TRAP_MODE = 7;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_SNMP_TRAP_ADRESS = 8;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_SNMP_AUTHENTIFICATION = 9;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_SNMP_COMMUNITY = 10;

	private const byte CMD_SYSTEM_CONFIGURATION_NETWORK_SNMP_RESET_TRAP_MODE_ADDRESS = 11;

	private const byte CMD_SYSTEM_CONFIGURATION_POWER_SYSTEM_TYPE = 48;

	private const byte CMD_SYSTEM_CONFIGURATION_POWER_MENU_IS_EXECUTABLE = 49;

	private const byte CMD_SYSTEM_CONFIGURATION_POWER_PACKAGED_STATUS = 50;

	private const byte CMD_SYSTEM_CONFIGURATION_POWER_STANDBY_MODE = 51;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_SYSTEM_TYPE = 80;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_MENU_IS_EXECUTABLE = 81;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_PACKAGED_STATUS = 82;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_CLOSED_CAPTION_MODE = 83;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_CLOSED_CAPTION_TYPE = 84;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_CLOSED_CAPTION_SERVICE_708 = 85;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_CLOSED_CAPTION_SERVICE_608 = 86;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_CLOSED_CAPTION_OSD_LEVEL = 87;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_AUDIO_LEVEL_METER_CH = 96;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_AUDIO_LEVEL_METER_TRANSPARENCY = 97;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_AUDIO_LEVEL_METER_POS = 98;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_AUDIO_LEVEL_METER_PEAK_HOLD = 99;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_TIME_CODE_VITC_LTC = 104;

	private const byte CMD_SYSTEM_CONFIGURATION_ON_SCREEEN_SET_TIME_CODE_POS = 105;

	private const byte CMD_SYSTEM_CONFIGURATION_DATETIME_SYSTEM_TYPE = 128;

	private const byte CMD_SYSTEM_CONFIGURATION_DATETIME_MENU_IS_EXECUTION = 129;

	private const byte CMD_SYSTEM_CONFIGURATION_DATETIME_PACKAGED_STATUS = 130;

	private const byte CMD_SYSTEM_CONFIGURATION_DATETIME_PACKAGED_SET = 131;

	private const byte CMD_SYSTEM_CONFIGURATION_PASSWORD_SYSTEM_TYPE = 160;

	private const byte CMD_SYSTEM_CONFIGURATION_PASSWORD_PACKAGED_STATUS = 161;

	private const byte CMD_SYSTEM_CONFIGURATION_PASSWORD_AUTHENTIFICATION = 162;

	private const byte CMD_SYSTEM_CONFIGURATION_PASSWORD_CHANGE = 163;

	private const byte CMD_SYSTEM_CONFIGURATION_PASSWORD_APPLY = 164;

	private const byte CMD_SYSTEM_CONFIGURATION_PASSWORD_LOCK = 165;

	private const byte CMD_SYSTEM_CONFIGURATION_RESTORE_FACTORY_SET_ALL = 224;

	private const byte CMD_ADJUSTMENT_AUTO_CHROMA_PHASE_SYSTEM_TYPE = 0;

	private const byte CMD_ADJUSTMENT_AUTO_CHROMA_PHASE_MENU_CAN_OPEN = 1;

	private const byte CMD_ADJUSTMENT_AUTO_CHROMA_PHASE_PACKAGED_STATUS = 2;

	private const byte CMD_ADJUSTMENT_AUTO_CHROMA_PHASE_EXECUTION_STATUS = 3;

	private const byte CMD_ADJUSTMENT_AUTO_CHROMA_PHASE_EXECUTION_STATUS_CLEAR = 4;

	private const byte CMD_ADJUSTMENT_AUTO_CHROMA_PHASE_EXECUTION = 5;

	private const byte CMD_ADJUSTMENT_AUTO_CHROMA_PHASE_COLOR_BAR_SETTING = 6;

	private const byte CMD_ADJUSTMENT_PICTURE_MANUAL_ADJUSTMENT_SYSTEM_TYPE = 32;

	private const byte CMD_ADJUSTMENT_PICTURE_MANUAL_ADJUSTMENT_MENU_CAN_OPEN = 33;

	private const byte CMD_ADJUSTMENT_PICTURE_MANUAL_ADJUSTMENT_PACKAGED_STATUS = 34;

	private const byte CMD_ADJUSTMENT_PICTURE_MANUAL_ADJUSTMENT_EXECUTION_STATUS = 35;

	private const byte CMD_ADJUSTMENT_PICTURE_MANUAL_ADJUSTMENT_EXECUTION_STATUS_CLEAR = 36;

	private const byte CMD_ADJUSTMENT_PICTURE_MANUAL_ADJUSTMENT_EXECUTION = 37;

	private const byte CMD_ADJUSTMENT_PHASE_PRESET_ADJUSTMENT_VALUE = 48;

	private const byte CMD_ADJUSTMENT_CHROMA_PRESET_ADJUST_VALUE = 49;

	private const byte CMD_ADJUSTMENT_BRIGHT_PREET_ADJUSET_VALUE = 50;

	private const byte CMD_ADJUSTMENT_CONTRAST_PREET_ADJUSET_VALUE = 51;

	private const byte CMD_ADJUSTMENT_PRESET_VALUE_SET_DETAIL = 52;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_SYSTEM_TYPE = 64;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_MENU_CAN_OPEN = 65;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_PACKAGED_STATUS = 66;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_EXECUTION_STATUS = 67;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_EXECUTION_STATUS_CLEAR = 68;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_EXECUTION = 69;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_TARGET_COLOR_TEMP_MODE = 70;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_CONTRAST_TARGET_LUMINANCE_VAULE = 71;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_PROBE_SETTING = 72;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_RESTORE_FACTORY_DATA = 73;

	private const byte CMD_ADJUSTMENT_MANUAL_COLOR_TEMPERATURE_ADJUSTMENT_SYSTEM_TYPE = 96;

	private const byte CMD_ADJUSTMENT_MANUAL_COLOR_TEMPERATURE_ADJUSTMENT_MENU_CAN_OPEN = 97;

	private const byte CMD_ADJUSTMENT_MANUAL_COLOR_TEMPERATURE_ADJUSTMENT_PACKAGED_STATUS = 98;

	private const byte CMD_ADJUSTMENT_MANUAL_COLOR_TEMPERATURE_ADJUSTMENT_EXECUTION_STATUS = 99;

	private const byte CMD_ADJUSTMENT_MANUAL_COLOR_TEMPERATURE_ADJUSTMENT_EXECUTION_STATUS_CLEAR = 100;

	private const byte CMD_ADJUSTMENT_MANUAL_COLOR_TEMPERATURE_ADJUSTMENT_EXECUTION = 101;

	private const byte CMD_ADJUSTMENT_MANUAL_COLOR_TEMPERATURE_ADJUSTMENT_RESET_ADJUSTING_COLOR_TEMP_VALUE = 102;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_Y_ADJUSTMENT_MODE = 103;

	private const byte CMD_ADJUSTMENT_MANUAL_COLOR_TEMPERATURE_ADJUSTMENT_INPUT_SIGNAL = 104;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_CONTRAST_BRIGHT_Y_ADJUSTMENT_EXECUTION = 105;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_INTERNAL_SIGNAL_LEVEL_CALC_EXECUTION = 106;

	private const byte CMD_ADJUSTMENT_MANUAL_COLOR_TEMPERATURE_ADJUSTMENT_RESET_ADJUSTING_CONTRAST_VALUE = 107;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_BACKLIGHT_VALUE = 104;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_USER_WB_BIAS_VALUE_FOR_MATRIX = 107;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_EXECUTION_BVM_E_F = 112;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_EXECUTION_PVMA_E_F = 112;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_EXECUTION_LMDA_E_F = 112;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_INTERNAL_SIGNAL = 113;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_PANEL_CORRECT_GAIN_VAL = 114;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_PANEL_CORRECT_BIAS_VAL = 115;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_USER_WB_GAIN_VAL = 116;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_USER_WB_BIAS_VAL = 117;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_TARGET_LUMI_MODE = 118;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_TARGET_VAL = 119;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_CONT_BRIGHT_HOLD_MODE = 120;

	private const byte CMD_ADJUSTMENT_LUMI_SENSOR_CALIBRATION_EXECUTION = 128;

	private const byte CMD_ADJUSTMENT_LUMI_SENSOR_CALIBRATION_EXECUTION_STATUS = 129;

	private const byte CMD_ADJUSTMENT_COLOR_TEMP_XY = 144;

	private const byte CMD_ADJUSTMENT_COLOR_TEMP_RGB = 145;

	private const byte CMD_ADJUSTMENT_COLOR_TEMPERATURE_ADJUSTMENT_COTRAST_HOLD_TIME = 146;

	private const byte CMD_ADJUSTMENT_COLOR_TEMPERATURE_ADJUSTMENT_SYNCHRONIZE = 147;

	private const byte CMD_ADJUSTMENT_COLOR_TEMPERATURE_RESTORE_FACTORY_EXECUTION = 148;

	private const byte CMD_ADJUSTMENT_POSITION_ADJUSTMENT_SYSTEM_TYPE = 176;

	private const byte CMD_ADJUSTMENT_POSITION_ADJUSTMENT_MENU_CAN_OPEN = 177;

	private const byte CMD_ADJUSTMENT_POSITION_ADJUSTMENT_PACKAGED_STATUS = 178;

	private const byte CMD_ADJUSTMENT_POSITION_ADJUSTMENT_EXECUTION_STATUS = 179;

	private const byte CMD_ADJUSTMENT_POSITION_ADJUSTMENT_EXECUTION_STATUS_CLEAR = 180;

	private const byte CMD_ADJUSTMENT_POSITION_ADJUSTMENT_EXECUTION = 181;

	private const byte CMD_ADJUSTMENT_POSITION_ADJUSTMENT_SHIFT = 182;

	private const byte CMD_ADJUSTMENT_WB_CORRECTION_VALUE_CLEAR = 224;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_SYSTEM_TYPE_BVM_X = 3;

	private const byte CMD_ADJUSTMENT_COMMON_COLOR_TEMPERTATURE_ADJUSTMENT_PASSWORD_LOCK_STATUS = 17;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_SYSTEM_TYPE_PVM_X = 3;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_SYSTEM_TYPE_BVM_HX = 3;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_SYSTEM_TYPE_PVM_XXX00 = 3;

	private const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_SYSTEM_TYPE_BVM_HXXX10 = 3;

	public const byte CMD_ADJUSTMENT_SENSE_RETURN_PASSWORD_LOCK_STATUS_UNLOCK = 1;

	public const byte CMD_ADJUSTMENT_SENSE_RETURN_PASSWORD_LOCK_STATUS_LOCK = 2;

	public const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_Y_ADJUSTMENT_MODE_PARAM_OFF = 1;

	public const byte CMD_ADJUSTMENT_AUTO_COLOR_TEMPERATURE_ADJUSTMENT_Y_ADJUSTMENT_MODE_PARAM_ON = 2;

	private const byte CMD_INFORMATION_SYSTEM_TYPE = 1;

	private const byte CMD_INFORMATION_MODEL_NAME = 2;

	private const byte CMD_INFORMATION_SERIAL_NUMBER = 3;

	private const byte CMD_INFORMATION_SOFTWARE_VERSION = 4;

	private const byte CMD_INFORMATION_OPERATION_TIME = 5;

	private const byte CMD_INFORMATION_BACKLIGHT_TIME = 6;

	private const byte CMD_INFORMATION_NETWORK_SWITCH = 16;

	private const byte CMD_INFORMATION_SLOT_NAME = 32;

	private const byte CMD_INFORMATION_SLOT_OPTION_MODEL_NAME = 33;

	private const byte CMD_INFORMATION_SLOT_SERIAL_NUMBER = 34;

	private const byte CMD_UNIVERSAL_FUNCTION_COMMON_POWER = 1;

	private const byte CMD_UNIVERSAL_FUNCTION_COMMON_CHAR_OFF_CONTROL = 2;

	private const byte CMD_UNIVERSAL_FUNCTION_COMMON_ERROR_NOTIFY_CLEAR = 3;

	private const byte CMD_UNIVERSAL_FUNCTION_COMMON_SELECT_CHANNEL_MEMORY = 17;

	private const byte CMD_UNIVERSAL_FUNCTION_COMMON_SELECT_QUAD_DISPLAY_MODE = 19;

	private const byte CMD_UNIVERSAL_FUNCTION_COMMON_QUADVIEW_MODE_FORMAT_SLOT_STATUS = 128;

	private const byte CMD_UNIVERSAL_FUNCTION_COMMON_CAN_TRANSIT_2K_HD_ZOOM_MODE = 129;

	private const byte LOW_LATENCY_TYPE_COMPONENT = 1;

	private const byte LOW_LATENCY_TYPE_HDMI = 2;

	private const byte LOW_LATENCY_MODE_DISABLE = 0;

	private const byte LOW_LATENCY_MODE_ENABLE = 1;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_SCANMODE = 1;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_ASPECT_MODE = 2;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_H_DELAY_MODE = 3;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_V_DELAY_MODE = 4;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_HV_DELAY_MODE = 5;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_H_DELAY_SLIDE_MODE = 6;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_V_DELAY_SLIDE_MODE = 7;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_MONO_MODE = 17;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_BLUE_ONLY_MODE = 18;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_R_OFF_MODE = 19;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_G_OFF_MODE = 20;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_B_OFF_MODE = 21;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_CHROMA_UP_MODE = 22;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_PEAK_WHITE_CONTROL = 23;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_PHASE_ADJUSTMENT_PRESET_MANUAL_MODE = 65;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_CHROMA_ADJUSTMENT_PRESET_MANUAL_MODE = 66;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_BRIGHTNESS_ADJUSTMENT_PRESET_MANUAL_MODE = 67;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_CONTRAST_ADJUSTMENT_PRESET_MANUAL_MODE = 68;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_APERTURE_MODE = 69;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_PHASE_ADJUST_VALUE = 81;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_CHROMA_ADJUST_VALUE = 82;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_BRIGHTNESS_ADJUST_VALUE = 83;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_CONTRAST_ADJUST_VALUE = 84;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_APERTURE_ADJUST_VALUE = 85;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_ASPECT_MODE_WITH_GROUP = 86;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_AUDIO_LEVEL_METER_MODE = 112;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_ALM_HOLD_RESET = 113;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_TIME_CODE_MODE = 114;

	private const byte CMD_UNIVERSAL_FUNCTION_DISPLAYING_FUNCTION_LOW_LATENCY_MODE = 224;

	private const byte CMD_UNIVERSAL_FUNCTION_SIGNAL_PATH_FUNCTION_EXTERNAL_SYNC_MODE = 2;

	private const byte CMD_UNIVERSAL_FUNCTION_MAKER_FUNCTION_MAKER_CONTROL = 1;

	private const byte CMD_UNIVERSAL_FUNCTION_MAKER_FUNCTION_ASPECT_MAKER_CONTROL = 2;

	private const byte CMD_UNIVERSAL_FUNCTION_MAKER_FUNCTION_AREA_MAKER_CONTROL = 3;

	private const byte CMD_UNIVERSAL_FUNCTION_FPD_LCD_UNIQUE_FUNCTION_BLACK_FRAME_INSERTION_CONTROL = 1;

	private const byte CMD_UNIVERSAL_FUNCTION_FPD_LCD_UNIQUE_FUNCTION_INTERLACE_CONTROL = 2;

	private const byte CMD_UNIVERSAL_FUNCTION_FPD_LCD_UNIQUE_FUNCTION_BLACK_DETAIL_MODE_CONTROL = 3;

	private const byte CMD_UNIVERSAL_FUNCTION_FPD_LCD_UNIQUE_FUNCTION_FOECE_SYNC_LOCK_MODE = 4;

	private const byte CMD_UNIVERSAL_FUNCTION_PICTURE_AND_PICTURE_FUNCTION_PP_SIDE_BY_SIDE_CONTROL = 1;

	private const byte CMD_UNIVERSAL_FUNCTION_PICTURE_AND_PICTURE_FUNCTION_PP_WIPE_CONTROL = 2;

	private const byte CMD_UNIVERSAL_FUNCTION_PICTURE_AND_PICTURE_FUNCTION_PP_BUTTERFLY_CONTROL = 3;

	private const byte CMD_UNIVERSAL_FUNCTION_PICTURE_AND_PICTURE_FUNCTION_PP_BLENDING_CONTROL = 4;

	private const byte CMD_UNIVERSAL_FUNCTION_ANALOG_FUNCTION_FILTER_SWITCH = 1;

	private const byte CMD_UNIVERSAL_FUNCTION_ANALOG_FUNCTION_COMBFILTER_CONTROL = 2;

	private const byte CMD_UNIVERSAL_FUNCTION_ANALOG_FUNCTION_YC_SEPARATION_CONTROL = 3;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_VERSION = 1;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_NAME = 17;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_DECODE_SETTING = 18;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_COLOR_TEMPERTURE_SETTING = 19;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_PICTURE_PRESET_BANK = 20;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_MATRIX_GAMMA_SETTING = 21;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_1080I_PSF_SETTING = 22;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_SCREEN_ASPECT_SETTING = 23;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_RGB_RANGE_AT_DVI = 24;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_FILM_CADENCE = 25;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_H_SHIFT = 26;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_SYNC_SETTING = 27;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_NTSC_SETUP_LEVEL = 28;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_COMPONENT_LEVEL = 29;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_BEATCAM_SETUP_LEVEL = 30;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_1125_SYSTEM = 31;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_AUTO_MATRIX_GAMMA_CONTROL_AT_HDMI_INPUT = 49;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_AUTO_ASPECT_CONTROL_AT_HDMI_INPUT = 50;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CAHNNEL_MEMORY_AUTO_RGB_RANGE_CONTROL_AT_HDMI_INPUT = 51;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CURRENT_MATRIX_GAMMA_CATEGORY = 80;

	private const byte CMD_DISPLAY_CONFIGURATION_INPUT_CONFIGURATION_CURRENT_1080I_PSF_CATEGORY = 81;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_SYSTEM_TYPE = 1;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_SETTING_EXECUTION = 5;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_PRESET_SETTING = 16;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_ASPECT_BLANKIG_MODE = 17;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_ASPECT_BLANKIG_LEVEL_SETTING = 18;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_ASPECT_MAKER_MODE = 32;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_ASPECT_MAKER_RATIO_SETTING = 33;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_ASPECT_MAKER_LINE_SETTING = 34;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_AREA_MAKER_MODE = 48;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_AREA_MAKER_ASPECT_RATIO_SETTING = 49;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_AREA_MAKER_AREA_SIZE_SETTING = 50;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_AREA_MAKER_SHAPE_MODE_SETTING = 51;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_AREA_MAKER_LINE_SETTING = 52;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_CENTER_MAKER_MODE = 80;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_CENTER_MAKER_LINE_SETTING = 81;

	private const byte CMD_DISPLAY_CONFIGURATION_MAKER_PRESET_MAKER_POSOTION_SETTING = 96;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP = 18;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_USER_GAMMA_SETTING = 19;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_USET_LUT_EXECUTION = 32;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_EMULATION_SETTING = 33;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_USET_LUT_SELECT = 34;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_USER_LUT_FILE_REGISTER = 35;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_USET_LUT_FILE_DELETE = 36;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_GAMUT_SELECT = 37;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_ASC_CDL_PROCESS = 48;

	private const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_ASC_ALL_PARAMETER = 49;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_1 = 1;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_2 = 2;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_3 = 3;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_4 = 4;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_5 = 5;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_XYZ = 16;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_1 = 33;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_2 = 34;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_3 = 35;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_4 = 36;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_5 = 37;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_6 = 38;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_7 = 39;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_8 = 40;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_9 = 41;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_10 = 42;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_11 = 43;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_12 = 44;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_13 = 45;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_14 = 46;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_15 = 47;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_16 = 48;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_17 = 49;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_18 = 50;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_19 = 51;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_20 = 52;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_21 = 53;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_22 = 54;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_23 = 55;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_24 = 56;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_25 = 57;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_26 = 58;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_27 = 59;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_28 = 60;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_29 = 61;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CH_30 = 62;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_USER_PRESET_CURRENT = byte.MaxValue;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_D65 = 1;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_D93 = 2;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_DCI = 3;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_D55 = 4;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_D61 = 5;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_D60 = 6;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_D50 = 7;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER1 = 17;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER2 = 18;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER3 = 19;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER4 = 20;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER5 = 21;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER6 = 22;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER7 = 23;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER8 = 24;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER9 = 25;

	public const byte CMD_DISPLAY_CONFIGURATION_COLOR_CUSTOMIZING_COLOR_TEMP_PARAM_COLOR_TEMP_USER10 = 26;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE_SYSTEM_TYPE = 1;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE_LINE_DISPLAY_SETTING = 17;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE_LINE_COLOR_SETTING = 18;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE_LINE_BLENDING_SETTING = 19;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE_SEPARATE_LINE_POSITION_SETTING = 20;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE_BLENDING_RATIO_SETTING = 21;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE_SIDE_BY_SIDE_LINE_SETTING = 25;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE_WIPE_LINE_SETTING = 26;

	private const byte CMD_DISPLAY_FUNCTION_PICTURE_AND_PICTURE_BUTTERFLY_LINE_SETTING = 27;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_SYSTEM_TYPE = 1;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_NOTIFICATION_CLEAR = 2;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_FUNCTION_ENABLE_SETTING = 16;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_DISPLAY_NOTIFICATION_SETTING = 17;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_DISPLAY_NOTIFICATION_RESET_SETTING = 18;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_INPUT_DETECYION_MODE_SETTING = 32;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_PIXEL_THRESHOLD_OF_INPUT_DETECTION_SETTING = 33;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_DETACTION_INPUT_SIGNAL_SIGNAL_LEVEL_SETTING = 34;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_POST_DETECTION_MODE_SETTING = 48;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_PIXEL_THRESHOLD_OF_POST_DETECTION_SETTING = 49;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_DETACTION_POST_SIGNAL_LEVEL_ADJUST = 50;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_ZEBRA_PATTERN_LINE_SETTING = 64;

	private const byte CMD_DISPLAY_FUNCTION_GAMUTE_ERROR_FUNCTION_GAMUT_ERROR_ZEBRA_PATTERN_MODULATION_SETTING = 65;

	private const byte CMD_DISPLAY_FUNCTION_INTERNAL_SIGNAL_SYSTEM_TYPE = 1;

	private const byte CMD_DISPLAY_FUNCTION_INTERNAL_SIGNAL_SIGNAL_APPLY = 2;

	private const byte CMD_DISPLAY_FUNCTION_PARALLEL_REMOTE_SYSTEM_TYPE = 1;

	private const byte CMD_DISPLAY_FUNCTION_PARALLEL_REMOTE_MODE = 2;

	private const byte CMD_DISPLAY_FUNCTION_VARIOUS_SETTING_SYSTEM_TYPE = 1;

	private const byte CMD_DISPLAY_FUNCTION_VARIOUS_SETTING_PIXEL_ZOOM_BOARDER_COLOR = 16;

	private const byte CMD_DISPLAY_FUNCTION_VARIOUS_SETTING_BLACKDETAIL_SETTING_CLIP_INDICATOR = 32;

	private const byte CMD_DISPLAY_FUNCTION_VARIOUS_SETTING_BLACKDETAIL_SETTING_ZEBRA_PATTERN = 33;

	private const byte CMD_COPY_SYSTEM_TYPE = 0;

	private const byte CMD_COPY_SYSTEM_SAVE_TO_MENU_IS_EXECUTABLE = 1;

	private const byte CMD_COPY_SYSTEM_CATEGORIZED_COPY_MENU_IS_EXECUTABLE = 2;

	private const byte CMD_COPY_SYSTEM_PRESET_VALUE_COPY_MENU_IS_EXECUTABLE = 3;

	private const byte CMD_COPY_SYSTEM_EXECUTION_STATUS = 4;

	private const byte CMD_COPY_SYSTEM_EXECUTION_STATUS_CLEAR = 5;

	private const byte CMD_COPY_SYSTEM_EXECUTION = 6;

	private const byte CMD_COPY_SYSTEM_BACKGROUND_EXECUTION = 7;

	private const byte CMD_COPY_SYSTEM_CHECK_SELF_CANSEL = 16;

	private const byte CMD_COPY_SYSTEM_CREATE_ORIGINAL_COPY_FILE = 32;

	private const byte CMD_COPY_SYSTEM_CATEGORIZED_COPY_EXECUTION = 48;

	private const byte CMD_COPY_SYSTEM_PRESET_VALUE_COPY_EXECUTION = 64;

	private const byte CMD_COPY_BACKUP_SYSTEM_EXECUTION = 128;

	private const byte CMD_COPY_BACKUP_SYSTEM_CREATE_BACKUP_FILE_EXECUTION = 129;

	private const byte CMD_COPY_BACKUP_SYSTEM_LOAD_BACKUP_FILE_EXECUTION = 130;

	private const byte CMD_AREA_SETTING_SYSTEM_TYPE = 0;

	private const byte CMD_AREA_SETTING_PACKAGED_SET = 1;

	private const byte CMD_PACKEGED_STATUS_MAIN_OPERATION_CONTROLS_PACKAGED_STATUS_SENSE = 1;

	private const byte CMD_PACKEGED_STATUS_MAIN_OPERATION_PIXEL_ZOOM_PACKAGED_STATUS_SENSE = 2;

	private const byte CMD_PACKEGED_STATUS_MAIN_OPERATION_CONFIGURATION_PACKAGED_STATUS_SENSE = 3;

	private const byte CMD_PACKEGED_STATUS_MAIN_OPERATION_ADVANCED_SETTING_PACKAGED_STATUS_SENSE = 4;

	private const byte CMD_PACKEGED_STATUS_MAIN_OPERATION_PRESET_MARKER_PACKAGED_STATUS_SENSE = 5;

	private const byte CMD_PACKEGED_STATUS_PICTURE_MANUAL_ADJUSTMENT_PACKAGED_STATUS = 6;

	private const byte CMD_PACKEGED_STATUS_AUTO_COLOR_TEMPERATURE_PACKAGED_STATUS = 7;

	private const byte CMD_PACKEGED_STATUS_MANUAL_COLOR_TEMPERATURE_PACKAGED_STATUS = 8;

	private const byte CMD_PACKEGED_STATUS_USER_MATRIX_GAMMA_PACKAGED_STATUS_SENSE = 9;

	private const byte CMD_PACKEGED_STATUS_PACKAGED_STATUS = 10;

	private const byte CMD_PACKEGED_STATUS_INTERNAL_SIGNAL_PACKAGED_STATUS_SENSE = 11;

	private const byte CMD_PACKEGED_STATUS_SYSTEM_CONFIGRATION_NETWORK_PACKAGED_STATUS = 12;

	private const byte CMD_PACKEGED_STATUS_SYSTEM_CONFIGRATION_POWER_PACKAGED_STATUS = 13;

	private const byte CMD_PACKEGED_STATUS_SYSTEM_CONFIGRATION_ON_SCREEN_SET_PACKAGED_STATUS = 14;

	private const byte CMD_PACKEGED_STATUS_SYSTEM_CONFIGRATION_DATE_TIME_PACKAGED_STATUS = 15;

	private const byte CMD_PACKEGED_STATUS_SYSTEM_CONFIGRATION_PASSWORD_PACKAGED_STATUS = 16;

	private const byte CMD_PACKEGED_STATUS_INFORMATION_COMMON_PACKAGED_STATUS = 17;

	private const byte CMD_PACKEGED_STATUS_INFORMATION_SCREEN_PACKAGED_STATUS = 18;

	private const byte CMD_PACKEGED_STATUS_GAMUT_ERROR_PACKAGED_STATUS_SENSE = 19;

	private const byte CMD_PACKEGED_STATUS_USET_LUT_FILE_MANAGER_PACKAGED_STATUS = 20;

	private const byte CMD_PACKEGED_STATUS_COPY_SYSTEM_PACKAGED_STATUS = 21;

	private const byte CMD_PACKEGED_STATUS_COLOR_TEMPARATURE_ADJUSTMENT_SYNCHONIZE_PACKAGED_STATUS = 22;

	private const byte CMD_PACKEGED_STATUS_PACKAGED_COMMON_STATUS = 32;

	public ushort dataLength
	{
		get
		{
			return length;
		}
		set
		{
		}
	}

	public LegacyVmsContainer(ref byte[] dt, ushort len)
	{
		data = dt;
		length = len;
	}

	public void setCommand(ref byte[] set_data, ushort len)
	{
		for (int i = 0; i < len; i++)
		{
			data[i] = set_data[i];
		}
		length = len;
	}

	public void systemGetPruductInformation()
	{
		data[0] = 128;
		data[1] = 0;
		length = 2;
	}

	public void systemSetStartControl()
	{
		data[0] = 0;
		data[1] = 1;
		length = 2;
	}

	public void systemConfigurationRestoreFactorySetAll()
	{
		data[0] = 8;
		data[1] = 224;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		length = 6;
	}

	public void adjustmentAutoColorTemperatureAdjustmentExecution()
	{
		data[0] = 16;
		data[1] = 69;
		length = 2;
	}

	public void adjustmentCommonColorTemperatureAdjustmentPasswordLockStatus()
	{
		data[0] = 144;
		data[1] = 17;
		length = 2;
	}

	public void adjustmentColorTemperatureAdjustmentSynchronize()
	{
		data[0] = 16;
		data[1] = 147;
		length = 2;
	}

	public void adjustmentColorTemperatureRestoreFactoryExecution()
	{
		data[0] = 16;
		data[1] = 148;
		length = 2;
	}

	public void adjustmentWBCorrectionValueClear()
	{
		data[0] = 16;
		data[1] = 224;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		length = 6;
	}

	public void adjustmentAutoColorTemperatureAdjustmentExecutionBvmEF(byte mode)
	{
		data[0] = 16;
		data[1] = 112;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustmentExecutionPvmaEF(byte mode)
	{
		data[0] = 16;
		data[1] = 112;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustmentExecutionLmdaEF(byte mode)
	{
		data[0] = 16;
		data[1] = 112;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustmentExecutionBvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 112;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustmentExecutionPvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 112;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustmentExecutionBvmhx(byte mode)
	{
		data[0] = 16;
		data[1] = 112;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustmentExecutionPvmxxx00(byte mode)
	{
		data[0] = 16;
		data[1] = 112;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustmentExecutionBvmhxxx10(byte mode)
	{
		data[0] = 16;
		data[1] = 112;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjInternalSignal(byte mode)
	{
		data[0] = 16;
		data[1] = 113;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjInternalSignalPvmaLmda(byte mode)
	{
		data[0] = 16;
		data[1] = 113;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjInternalSignalBvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 113;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjInternalSignalPvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 113;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjInternalSignalBvmhx(byte mode)
	{
		data[0] = 16;
		data[1] = 113;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjInternalSignalPvmxxx00(byte mode)
	{
		data[0] = 16;
		data[1] = 113;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjInternalSignalBvmhxxx10(byte mode)
	{
		data[0] = 16;
		data[1] = 113;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjPanelCorrectBiasVal(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 115;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		Array.Copy(set_data, 0, data, 6, 6);
		length = 12;
	}

	public void adjustmentAutoColorTempAdjPanelCorrectGainVal(bool isStatusSence, byte[] VmsRgbStructure)
	{
		data[0] = 16;
		data[1] = 114;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		Array.Copy(VmsRgbStructure, 0, data, 6, 24);
		length = 30;
	}

	public void adjustmentAutoColorTempAdjUserWbBiasVal(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 117;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		Array.Copy(set_data, 0, data, 6, 12);
		length = 18;
	}

	public void adjustmentAutoColorTempAdjUserWbBiasValPvmaLmda(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 117;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		Array.Copy(set_data, 0, data, 6, 12);
		length = 18;
	}

	public void adjustmentAutoColorTempAdjUserWbBiasValBvmx(bool isStatusSence, VmsBiasSettingMode type, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 117;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		switch (type)
		{
		case VmsBiasSettingMode.IMPROVED_BLACK_SCALE:
			data[18] = 2;
			break;
		case VmsBiasSettingMode.NORMAL:
			data[18] = 1;
			break;
		}
		length = 19;
	}

	public void adjustmentAutoColorTempAdjUserWbBiasValPvmx(bool isStatusSence, VmsBiasSettingMode type, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 117;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		switch (type)
		{
		case VmsBiasSettingMode.IMPROVED_BLACK_SCALE:
			data[18] = 2;
			break;
		case VmsBiasSettingMode.NORMAL:
			data[18] = 1;
			break;
		}
		length = 19;
	}

	public void adjustmentAutoColorTempAdjUserWbBiasValBvmhx(bool isStatusSence, VmsBiasSettingMode type, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 117;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		switch (type)
		{
		case VmsBiasSettingMode.IMPROVED_BLACK_SCALE:
			data[18] = 2;
			break;
		case VmsBiasSettingMode.NORMAL:
			data[18] = 1;
			break;
		}
		length = 19;
	}

	public void adjustmentAutoColorTempAdjUserWbBiasValPvmxxx00(bool isStatusSence, VmsBiasSettingMode type, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 117;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		switch (type)
		{
		case VmsBiasSettingMode.IMPROVED_BLACK_SCALE:
			data[18] = 2;
			break;
		case VmsBiasSettingMode.NORMAL:
			data[18] = 1;
			break;
		}
		length = 19;
	}

	public void adjustmentAutoColorTempAdjUserWbBiasValBvmhxxx10(bool isStatusSence, VmsBiasSettingMode type, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 117;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		switch (type)
		{
		case VmsBiasSettingMode.IMPROVED_BLACK_SCALE:
			data[18] = 2;
			break;
		case VmsBiasSettingMode.NORMAL:
			data[18] = 1;
			break;
		}
		length = 19;
	}

	public void adjustmentAutoColorTempAdjUserWbGainVal(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 116;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		Array.Copy(set_data, 0, data, 6, 12);
		length = 18;
	}

	public void adjustmentAutoColorTempAdjUserWbGainValPvmaLmda(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 116;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		Array.Copy(set_data, 0, data, 6, 12);
		length = 18;
	}

	public void adjustmentAutoColorTempAdjUserWbGainValBvmx(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 116;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		length = 18;
	}

	public void adjustmentAutoColorTempAdjUserWbGainValPvmx(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 116;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		length = 18;
	}

	public void adjustmentAutoColorTempAdjUserWbGainValBvmhx(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 116;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		length = 18;
	}

	public void adjustmentAutoColorTempAdjUserWbGainValPvmxxx00(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 116;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		length = 18;
	}

	public void adjustmentAutoColorTempAdjUserWbGainValBvmhxxx10(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 116;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 12);
		length = 18;
	}

	public void adjustmentAutoColorTempAdjBacklightValLmda(bool isStatusSence, byte[] set_data)
	{
		data[0] = 16;
		data[1] = 104;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 2;
			return;
		}
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		data[6] = 0;
		data[7] = 0;
		Array.Copy(set_data, 0, data, 8, 2);
		length = 10;
	}

	public void adjustmentAutoColorTempAdjTargetLumiMode()
	{
		data[0] = 144;
		data[1] = 118;
		length = 2;
	}

	public void adjustmentAutoColorTempAdjTargetVal(byte[] set_data)
	{
		data[0] = 16;
		data[1] = 119;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		Array.Copy(set_data, 0, data, 6, 8);
		length = 14;
	}

	public void adjustmentAutoColorTempAdjTargetValPvmaLmda(byte[] set_data)
	{
		data[0] = 16;
		data[1] = 119;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		Array.Copy(set_data, 0, data, 6, 8);
		length = 14;
	}

	public void adjustmentAutoColorTempAdjTargetValBvmx(byte[] set_data)
	{
		data[0] = 16;
		data[1] = 119;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 8);
		length = 14;
	}

	public void adjustmentAutoColorTempAdjTargetValPvmx(byte[] set_data)
	{
		data[0] = 16;
		data[1] = 119;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 8);
		length = 14;
	}

	public void adjustmentAutoColorTempAdjTargetValBvmhx(byte[] set_data)
	{
		data[0] = 16;
		data[1] = 119;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 8);
		length = 14;
	}

	public void adjustmentAutoColorTempAdjTargetValPvmxxx00(byte[] set_data)
	{
		data[0] = 16;
		data[1] = 119;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 8);
		length = 14;
	}

	public void adjustmentAutoColorTempAdjTargetValBvmhxxx10(byte[] set_data)
	{
		data[0] = 16;
		data[1] = 119;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		Array.Copy(set_data, 0, data, 6, 8);
		length = 14;
	}

	public void adjustmentAutoColorTempAdjContBrightHoldMode(byte mode)
	{
		data[0] = 16;
		data[1] = 120;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjContBrightHoldModePvmaLmda(byte mode)
	{
		data[0] = 16;
		data[1] = 120;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjContBrightHoldModeBvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 120;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTempAdjContBrightHoldModePvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 120;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustYAdjustmentMode(byte mode)
	{
		data[0] = 16;
		data[1] = 103;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustYAdjustmentModeBvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 103;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustYAdjustmentModePvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 103;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustYAdjustmentModeBvmhx(byte mode)
	{
		data[0] = 16;
		data[1] = 103;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustYAdjustmentModePvmxxx00(byte mode)
	{
		data[0] = 16;
		data[1] = 103;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustYAdjustmentModeBvmhxxx10(byte mode)
	{
		data[0] = 16;
		data[1] = 103;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustContrastBrightYAdjustmentExecution(byte mode)
	{
		data[0] = 16;
		data[1] = 105;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustContrastBrightYAdjustmentExecutionBvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 105;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustContrastBrightYAdjustmentExecutionPvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 105;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustContrastBrightYAdjustmentExecutionBvmhx(byte mode)
	{
		data[0] = 16;
		data[1] = 105;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustContrastBrightYAdjustmentExecutionPvmxxx00(byte mode)
	{
		data[0] = 16;
		data[1] = 105;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustContrastBrightYAdjustmentExecutionBvmhxxx10(byte mode)
	{
		data[0] = 16;
		data[1] = 105;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustInternalSignalLevelCalcExecution(byte mode)
	{
		data[0] = 16;
		data[1] = 106;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 2;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustInternalSignalLevelCalcExecutionBvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 106;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentAutoColorTemperatureAdjustInternalSignalLevelCalcExecutionPvmx(byte mode)
	{
		data[0] = 16;
		data[1] = 106;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentLumiSensorCalibrationExecution(byte mode)
	{
		data[0] = 16;
		data[1] = 128;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		data[6] = mode;
		length = 7;
	}

	public void adjustmentLumiSensorCalibrationExecutionStatus()
	{
		data[0] = 144;
		data[1] = 129;
		length = 2;
	}

	public void informationGetMonitorNetworkSwitch()
	{
		data[0] = 152;
		data[1] = 16;
		length = 2;
	}

	public void universalFunctionCommonQuadviewModeFormatSlotState()
	{
		data[0] = 32;
		data[1] = 128;
		length = 2;
	}

	public void universalFunctionCanTransit2KHdZoomMode()
	{
		data[0] = 32;
		data[1] = 129;
		length = 2;
	}

	public void universalFunctionDisplayFunctionLowLatencyModeSet(bool lowLatencyMode)
	{
		data[0] = 33;
		data[1] = 224;
		data[2] = 2;
		if (lowLatencyMode)
		{
			data[3] = 1;
		}
		else
		{
			data[3] = 0;
		}
		length = 4;
	}

	public void universalFunctionDisplayFunctionLowLatencyModeSence()
	{
		data[0] = 161;
		data[1] = 224;
		length = 2;
	}

	public void colorCustomizingUserLutExecution()
	{
		data[0] = 52;
		data[1] = 32;
	}

	public void colorCustomizingUserLutSelect()
	{
		data[0] = 52;
		data[1] = 34;
	}

	public void colorCustomizingUserLutFileRegister()
	{
		data[0] = 52;
		data[1] = 35;
	}

	public void colorCustomizingUserLutFileDelete()
	{
		data[0] = 52;
		data[1] = 36;
	}

	public void colorCustomizingColorGamutSelect()
	{
		data[0] = 52;
		data[1] = 37;
	}

	public void colorCustomizingAscAllParameter()
	{
		data[0] = 52;
		data[1] = 49;
	}

	public void colorCustomizingAscCdlProcess()
	{
		data[0] = 52;
		data[1] = 48;
	}

	public void colorCustomizingColorTemp(bool isStatusSence, byte userPreset, byte colorTemp)
	{
		data[0] = 52;
		data[1] = 18;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 3;
		data[6] = 0;
		data[7] = userPreset;
		if (isStatusSence)
		{
			data[0] |= 128;
			length = 8;
		}
		else
		{
			data[8] = colorTemp;
			length = 9;
		}
	}

	public void copySystemPresetValueCopyExecution()
	{
		data[0] = 80;
		data[1] = 64;
		length = 2;
	}

	public void copySystemBackupSystemExecution(bool mode)
	{
		data[0] = 80;
		data[1] = 128;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		if (mode)
		{
			data[6] = 1;
		}
		else
		{
			data[6] = 4;
		}
		length = 7;
	}

	public void copySystemBackupSystemCreateBackupFileExecution()
	{
		data[0] = 80;
		data[1] = 129;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		length = 6;
	}

	public void copySystemBackupSystemLoadExecution()
	{
		data[0] = 80;
		data[1] = 130;
		data[2] = 0;
		data[3] = 0;
		data[4] = 0;
		data[5] = 1;
		length = 6;
	}

	public void packagedStatusSystemConfigurationOnScreenSetPackagedStatus()
	{
		data[0] = 96;
		data[1] = 14;
		length = 2;
	}

	public void packagedStatusColorTemparatureAdjustmentSynchronizePackagedStatus()
	{
		data[0] = 96;
		data[1] = 22;
		length = 2;
	}

	public void packagedStatusInformationCommonPackagedStatus()
	{
		data[0] = 224;
		data[1] = 17;
		length = 2;
	}

	public void packagedStatusPackagedCommonStatus()
	{
		data[0] = 224;
		data[1] = 32;
		length = 2;
	}

	public void packagedStatusMainOperationConfigurationPackegedStatusSense()
	{
		data[0] = 224;
		data[1] = 3;
		data[2] = byte.MaxValue;
		length = 3;
	}
}
